baseURL           = "https://example.com/"
title             = "SUN"
languageCode      = "en-us"
theme             = "sun-theme"
enableRobotsTXT   = true
pluralizeListTitles = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
    ordered    = false

[params]
  author       = "SUN"
  description  = "In Praise Of The Sun"
  keywords     = ["SUN"]
  images       = ["sun.svg"]
